### ISSUE TITLE
Error: Cannot find module 'form-data'

### ISSUE THREAD

**Issue by argyleink** [johngeorgewright/grunt-http#19]
2 optional dependencies fail, which may or may not be ok. But I'm not able to use the plugin, getting a form-data error.

2 failing deps:
- npm WARN optional dep failed, continuing hawk@~2.3.0  
- npm WARN optional dep failed, continuing form-data@0.1.4

**Comment by cubicrace** [comment]
npm install --save module_name

For example: If the error is: { [Error: Cannot find module '/root/.npm/form-data'] code: 'MODULE_NOT_FOUND' } then you can resolve this issue by executing the command:

npm install --save form-data

**Comment by declanfleming** [comment]
> npm install --save module_name
> 
> For example: If the error is: { [Error: Cannot find module '/root/.npm/form-data'] code: 'MODULE_NOT_FOUND' } then you can resolve this issue by executing the command:
> 
> npm install --save form-data

Thank you so much!  this saved me a lot of frustration this week!

D
