### ISSUE TITLE
Security issue: Prototype pollution attack(Introduced by the hoek@3.0.4, the dependency of hawk@4.1.2)

### ISSUE THREAD

**Issue by MichaelTsengLZ** [johngeorgewright/grunt-http#30]
The latest version grunt-http@2.3.0 uses hawk ^4.0.0. However, hawk@4.1.2 has a vulnerability which is introduced by hoek@3.0.4. More information is here:

https://nodesecurity.io/advisories/566
https://snyk.io/vuln/npm:hoek:20180212

Could you please update hawk to the latest version to solve the vulnerability? Thank you so much.

**Comment by johngeorgewright** [comment]
Released as version v2.3.1
